version: '3.8'

services:
  credit-risk-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory into the container's /app directory
      # This allows for live code changes during development without rebuilding the image
      - .:/app
    # Command to run the application (overrides CMD in Dockerfile for dev)
    # This ensures the API restarts if code changes are detected
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # Example environment variables (if any needed by your app)
      # - API_KEY=your_secret_key
      PYTHONUNBUFFERED: 1 # Ensure Python output is unbuffered
